services:
  db:
    image: postgres:15
    container_name: dbveiculos
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: dbveiculos
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-veiculos
    restart: unless-stopped
    environment:
      # string de conexão apontando para o serviço "db"
      ConnectionStrings__VeiculoDb: "Host=db;Port=5432;Database=dbveiculos;Username=postgres;Password=senha"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db-data:
